// <auto-generated />
namespace Battleships.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RenamePictureNameToPictureFileName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamePictureNameToPictureFileName));
        
        string IMigrationMetadata.Id
        {
            get { return "201407231457533_RenamePictureNameToPictureFileName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
