// <auto-generated />
namespace Battleships.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddGameResults : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGameResults));
        
        string IMigrationMetadata.Id
        {
            get { return "201407150903076_AddGameResults"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
